frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\ProductsSearch;
use yii\web\Controller;
use common\models\Categories;
use yii\web\NotFoundHttpException;
use common\models\Products;
use yii\web\Response;
use common\models\Modells;

class CategoryController extends Controller
{
    public function actionView($id)
    {
        $category = $this->findCategory($id);

        $searchModel = new ProductsSearch();
        $searchModel->category_id = $category->id;
        $searchModel->load(Yii::$app->request->queryParams);
        $dataProvider = $searchModel->searchAdmin(Yii::$app->request->get('ProductsFilter'));

        return $this->render('index', [
            'category' => $category,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCompare($id)
    {
        $products= $this->findProductsParent($id);
        
        $searchModel = new ProductsSearch();
        $searchModel->parent_id = $products->id;
        //$searchModel->load(Yii::$app->request->queryParams);
        $dataProvider = $searchModel->searchChild();

        return $this->render('compare', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionGetModellsByBrand()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $res = [];
        $model= null;
        if (Yii::$app->request->post('depdrop_parents')[0]) {
            $model = Modells::getAll(Yii::$app->request->post('depdrop_parents')[0]);
        }

        foreach ($model as $item) {
            $res[] = ['id' => $item->id, 'name' => $item->name];
        }

        return ['output' => $res, 'selected' => ''];
    }
    
    protected function findCategory($id)
    {
        if (($model = Categories::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The operation (#' . $id . ') does not exist.');
        }
    }
    
    protected function findProductsParent($id)
    {
        if (($model = Products::find()->where(['id' => $id])->andWhere([
                    "OR",
                    ['parent_id' => 0],
                    ['parent_id' => null],
                ])
                ->andWhere([
                    "OR",
                    ['shop_id' => 0],
                    ['shop_id' => null],
                ])->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The operation (#' . $id . ') does not exist.');
        }
    }
}

frontend/views/category/_left-search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use common\models\Attributes;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;
use common\models\Brands;
use common\models\CategoriesAttributes;
use kartik\checkbox\CheckboxX;

/* @var $this yii\web\View */
/* @var $model frontend\models\ProductsSearch */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="panel panel-default">
    <h4 class="refineby-style">REFINE BY</h4>
    <div class="panel-body">
        <?php foreach ($category->getAttributeForFilter(10, CategoriesAttributes::FILTER_TYPE_LEFT) as $attribute) { ?>
            <div class="col-md-12 filter-item">
                <h5 class="refineby-category-name"><div class="refineby-category-triangles"></div><?= $attribute->name; ?></h5>
                <?php foreach ($attribute->getAttributesValueArray() as $aVId => $aValue) { ?>
                <div class="checkbox-style">
                        <?= CheckboxX::widget([
                            'name' => 'ProductsFilter[' . $attribute->id . ']['.$aVId.']',
                            'value' => isset($_GET['ProductsFilter'][$attribute->id][$aVId]) ? $_GET['ProductsFilter'][$attribute->id][$aVId] : null,
                            'options' => [
                                'class' => 'js-filter-left-sidebar',
                                'data-attribute' => $attribute->id,
                                'data-value' => $aVId
                            ],
                            'pluginOptions' => [
                                'threeState' => false,
                                'iconChecked' => '<span class="checked-filter-items"></span>',
                            ]
                        ]); ?>
                        <label class="refineby-category-items"><?= $aValue; ?></label>
                    </div>
                <?php } ?>
            </div>
<!--        <hr style="border-color:white !important;">-->
        <?php }  ?>
    </div>
</div>
<script>
    $(function(){
        $(document).on('change', '.js-filter-left-sidebar', function(){
            var attrId = $(this).data('attribute');
            var attrValId = $(this).data('value');
            var checkbox = $('#product_filter_' + attrId + '_' + attrValId);
            if (checkbox.length) {
                checkbox.val($(this).val())
            }
            $('#form-category-filter').submit()
        })
    })
    $(document).ready(function(){
        $( ".refineby-category-name" ).on( "click", function() {
            $( this ).parent().toggleClass('filter-item-animate')
        });
    });
</script>

frontend/views/category/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use common\models\Attributes;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;
use common\models\Brands;
use common\models\CategoriesAttributes;
/* @var $this yii\web\View */
/* @var $model frontend\models\ProductsSearch */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="panel panel-default">
    <div class="panel-body">
        <?php  $form = ActiveForm::begin([
            'id' => 'form-category-filter',
            'action' => ['/category/' . $category->id],
            'method' => 'get',
        ]); ?>

        <?php if ($category->categoriesAttributeModel) { ?>
            <div class="row">
                <div class="col-md-3 filter-item">
                    <?= $form->field($model, 'brand_id')->widget(Select2::classname(), [
                        'data' => Brands::getAllArrayMapByCategory($category->id),
                        'language' => 'en',
                        'size' => Select2::MEDIUM,
                        'options' => ['placeholder' => 'Select Brand...'],
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ])->label(false); ?>
                </div>

                <div class="col-md-3 filter-item">
                    <?= $form->field($model, 'modells_id', ['options' => ['class' => 'col-xs-12', 'style' => 'padding: 0']])
                        ->widget(DepDrop::className(), [
                            'type' => DepDrop::TYPE_SELECT2,
                            'options' => ['placeholder' => Yii::t('app', 'Select...')],
                            'select2Options' => [
                                'pluginOptions' => [
                                    'allowClear' => true
                                ]
                            ],
                            'pluginOptions' => [
                                'placeholder' => Yii::t('app', 'Select...'),
                                'initialize' => true,
                                'initDepends' => ['productssearch-brand_id'],
                                'loadingText' => Yii::t('app', 'Select Model...'),
                                'depends' => ['productssearch-brand_id'],
                                'url' => Url::to(['/category/get-modells-by-brand']) . '/' . $model->modells_id,
                            ],
                        ])->label(false) ?>
                </div>

                <?php foreach ($category->getAttributeForFilter(2, CategoriesAttributes::FILTER_TYPE_UP) as $attribute) { ?>
                    <div class="col-md-3 filter-item">
                        <?= Select2::widget([
                            'name' => 'ProductsFilter[' . $attribute->id . ']',
                            'value' => isset($_GET['ProductsFilter'][$attribute->id]) ? $_GET['ProductsFilter'][$attribute->id] : null,
                            'data' => $attribute->getAttributesValueArray(),
                            'options' => ['placeholder' => 'Select a ' . $attribute->name . ' ...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ],
                        ]);  ?>
                    </div>
                <?php }  ?>
                
            </div>
        <?php } ?>

        <?php foreach ($category->getAttributeForFilter(100, CategoriesAttributes::FILTER_TYPE_LEFT) as $attribute) { ?>
            <?php foreach ($attribute->getAttributesValueArray() as $aVId => $aValue) { ?>
                <?= Html::hiddenInput('ProductsFilter[' . $attribute->id . ']['.$aVId.']', isset($_GET['ProductsFilter'][$attribute->id][$aVId]) ? $_GET['ProductsFilter'][$attribute->id][$aVId] : null, [
                    'id' => 'product_filter_' . $attribute->id . '_' . $aVId
                ]); ?>
            <?php } ?>
        <?php } ?>

        <div class="row">
            <div class="col-md-3 filter-item">
                <?= $form->field($model, 'price_from')->input('number', ['placeholder' => 'Min Price'])->label(false) ?>
            </div>
            <div class="col-md-3 filter-item">
                <?= $form->field($model, 'price_to')->input('number',['placeholder' => 'Max Price'])->label(false) ?>
            </div>
            <div class="col-md-3 filter-item">
                <?= Html::submitButton('<i class="ion-search"></i>', ['class' => 'search-btn']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

frontend/views/category/compare.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use frontend\widgets\SponsoredProducts;
use yii\widgets\LinkPager;


/* @var $this yii\web\View */
/* @var $searchModel frontend\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Searches for Result';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-compare">
    <section class="compare">
        <div class="container">
            <div class="section-head"><?= $this->title; ?></div>
        </div>
        <div class="container">
            <div class="sub-head">Results</div>
            <div class="row product-list" style="margin-top: 10px;">
                <?php if (count($dataProvider->getModels()) > 0){ ?>
                    <?php foreach ($dataProvider->getModels() as $product) { ?>
                        <div class="col-6 col-md-3 pr-it-1">
                            <div class="product-item">
                                <div class="product-image">
                                <a href="<?= $product->getLink(); ?>" class="align-self-center"><img src="<?= $product->getImages(); ?>" alt="<?= $product->name; ?>" class="align-self-center"></a>
                                </div>
                                <div class="product-name">
                                    <?= $product->name; ?>
                                </div>
                                <div class="product-price">
                                    From - <?= $product->getPrice(); ?>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                <?php } else{ ?>
                    <div class="col-12 info">
                        No product
                    </div>
                <?php } ?>
            </div>
            <div class="pagination-pages">
            <?= LinkPager::widget([
                'pagination' => $dataProvider->pagination,
                'firstPageLabel' => 'First',
                'lastPageLabel' => 'Last',
                'pageCssClass' => 'page',
            ]); ?>
            </div>
        </section>
    </div>
</div>

frontend/views/category/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use frontend\widgets\SponsoredProducts;
use yii\widgets\LinkPager;


/* @var $this yii\web\View */
/* @var $searchModel frontend\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = $category->name;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-category">
    <section class="category-filter">
    <div class="container">
        <div class="post-category-head">Searches for <?= $this->title; ?></div>
        <?= $this->render('_search', ['model' => $searchModel, 'category' => $category]); ?>
    </div>
    </section>
    <section class="sponsored">
        <div class="container">
            <div class="post-category-head text-left">Sponsored Links</div>
            <?= SponsoredProducts::widget(['categoryId' => $category->id, 'limit' => 4]); ?>
        </div>
    </section>
    <section class="newest-listed">
        <div class="container">
            <div class="post-category-head text-left">Newest <?= $this->title; ?> Listed</div>
            <div class="row product-list" style="margin-top: 60px;">
                <div class="col-sm-12 col-md-4 col-lg-3 col-xl-3">
                    <?= $this->render('_left-search', ['model' => $searchModel, 'category' => $category]); ?>
                </div>
                <div class="col-sm-12 col-md-8 col-lg-9 col-xl-9">
                    <div class="row">
                        <?php if (count($dataProvider->getModels()) > 0){ ?>
                            <?php foreach ($dataProvider->getModels() as $product) { ?>
                                <div class="col-12 pr-it">
                                    <div class="row product-item justify-content-center">
                                        <div class="col-8 col-md-6 col-lg-3 col-xl-3">
                                            <div class="product-image">
                                                <img src="<?= $product->getImages(); ?>" alt="<?= $product->name; ?>" class="align-self-center">
                                            </div>
                                        </div>
                                        <div class="col-11 col-md-9 col-lg-7 col-xl-7 product-items-decriptiom">
                                            <div class="product-name">
                                                <h4 style="color:black;"><a href="<?= $product->getLink(); ?>"><?= $product->name; ?></a></h4>
                                            </div>
                                            <div class="product-description" style="color:black;">
                                                <?= $product->description; ?>
                                            </div>
                                        </div>
                                        <div class="col-4 col-md-3 col-lg-2 col-xl-2">
                                            <div class="product-price">
                                                <?= $product->getPrice(); ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row product-item-other-img">
                                        <?php foreach ($product->productsImagesModel as $image) { ?>
                                            <img src="<?= $image->getImages(); ?>" class="thumbnail-img">
                                        <?php } ?>
                                    </div>
                                </div>
                            <?php } ?>
                        <?php } else{ ?>
                            <div class="col-12 info">
                                No product
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="pagination-pages">
            <?= LinkPager::widget([
                'pagination' => $dataProvider->pagination,
                'firstPageLabel' => 'First',
                'lastPageLabel' => 'Last',
                'pageCssClass' => 'page',
            ]); ?>
            </div>
        </div>
    </section>
</div>


<?php /*>
 * <div class="col-sm-9">
                    <div class="row">
                        <?php if (count($dataProvider->getModels()) > 0){ ?>
                            <?php foreach ($dataProvider->getModels() as $product) { ?>
                                <div class="col-6 col-md-3 pr-it">
                                    <div class="product-item">
                                        <div class="product-image">
                                            <img src="<?= $product->getImages(); ?>" alt="<?= $product->name; ?>" class="align-self-center">
                                        </div>
                                        <div class="product-name">
                                            <?= $product->name; ?>
                                        </div>
                                        <div class="product-price">
                                            From - <?= $product->getPrice(); ?>
                                        </div>
                                        <div class="product-link">
                                            <a href="<?= $product->getLink(); ?>">Compare prices</a>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        <?php } else{ ?>
                            <div class="col-12 info">
                                No product
                            </div>
                        <?php } ?>
                    </div>
                </div>
 * 
<?php */ ?>
<script>
    $(document).ready(function(){
        if($(window).width() <= 414){
            var height = $('.product-image').width();
        }else if($(window).width() <= 991){
            var height = $('.product-image').width() + 75;
        }else{
            var height = $('.product-image').width() - 79;
        }
        $('.product-image').css({
            height : height 
        });
        $( window ).resize(function() {
             if($(window).width() <= 414){
                var height = $('.product-image').width();
            }else if($(window).width() <= 991){
                var height = $('.product-image').width() + 75;
            }else{
                var height = $('.product-image').width() - 79;
            }
            $('.product-image').css({
                height : height 
            });
        });
    });
</script>